resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: keycloak-env
  literals:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    - KC_HEALTH_ENABLED=true
    - KC_HTTP_ENABLED=true
    - KC_HOSTNAME_STRICT=false
    - KC_PROXY=edge
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=keycloak

