resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: bamboocards-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=sVqnd9qLTLYgWjIqdHqoAY
    - REDIS_URI=redis://:{redis-password-uri-encoded.value}@redis:6379
    - KEYCLOAK_HTTP=http://keycloak:8080
    - services__keycloak__http__0=http://keycloak:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=BambooCards
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: bamboocards-secrets
  envs:
  - .bamboocards.secrets
